behaviors:
  CarBrain:
    trainer_type: ppo
    hyperparameters:
      batch_size: 2048
      buffer_size: 20480
      learning_rate: 0.0003
      beta: 0.01
      epsilon: 0.25
      lambd: 0.95
      num_epoch: 3
      learning_rate_schedule: linear
    network_settings:
      hidden_units: 512
      num_layers: 2
      normalize: true
    reward_signals:
      extrinsic:
        strength: 1.0
        gamma: 0.99
    max_steps: 1000000
    time_horizon: 256
    summary_freq: 10000